kind: Service
apiVersion: v1
metadata:
  name: rill-flow-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    rill-flow: rill-flow
  ports:
    - name: backend-port
      port: 8080
      targetPort: 8080
      protocol: TCP

